csf_detection_web/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('detect.urls', namespace="detect"))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detect/urls.py
from django.urls import path
from . import views

app_name = "detect"

urlpatterns = [
    path('', views.home, name='home'),
    path('upload/',views.save_files,name="upload"),
    path('result/', views.result, name='result')
]

detect/models.py
from django.db import models

# Create your models here.
class uploadfile(models.Model):
    patient=models.CharField(max_length=255)
    files=models.FileField(upload_to="")


    

detect/views.py
from django.shortcuts import render,HttpResponse
from . import predict
from . models import uploadfile
import os

# our home page view
def home(request):    
    return render(request, 'index.html')
        
def save_files(request):
    if request.method == "POST":
        name=request.POST.get("patient")
        di=request.FILES.getlist("files")
        uploadfile.objects.all().delete()
        for f in di:
            uploadfile(patient=name, files=f,).save()
        return result(request)

# our result page view
def result(request):
    result = predict.pred()
    print(result)
    s=""
    if result[7]>0.5:
        s+="** FRACTURED **"
        ind=result.index(max(result[:7]))
        s+="\nPredicted fracture at C"+str(ind+1)
    else:
        s+="** NOT FRACTURED **"

    return HttpResponse(s)

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meata http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> CSF Upload dicom files</title>
    </head>
    <body>
        <form action="{% url 'detect:upload' %}" method='POST' enctype="multipart/form-data">
            <input type="text" name="patient" placeholder="Enter patient id/name">
            <input type="file" multiple name="files">
            {% csrf_token %}
            <button type="submit" name="predict">Predict</button>
        </form>
</html>